version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

commands:
  ecr_publish:
    parameters:
      tag:
        type: string
      accountUrl:
        type: string
    steps:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          account-url: <<parameters.accountUrl>>
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET
          repo: ${MY_APP_PREFIX}
          tag: <<parameters.tag>>

jobs:
  PublishProd:
    executor: aws-ecr/default
    steps:
      - ecr_publish:
          tag: "latest"
          accountUrl: AWS_ECR_ACCOUNT_URL

workflows:
  BuildDeploy:
    jobs:
      - Authorization:
          type: approval
          filters:
            branches:
              only:
                - main
                - story/CBLT-37
      - PublishProd:
          requires:
            - Authorization
          filters:
            branches:
              only:
                - main
                - story/CBLT-37
